/* import { Geist, Geist_Mono } from "next/font/google"; */
import "./globals.css";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />

export const metadata = {
  title: "HealthyTeen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{ fontFamily: "sans-serif" }}
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
